// Code generated by goctl. DO NOT EDIT!
// Source: worker.proto

package workerclient

import (
	"context"

	"github.com/Awadabang/wasser/types/worker"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LifeCircleReq  = worker.LifeCircleReq
	LifeCircleResp = worker.LifeCircleResp
	StatusSyncReq  = worker.StatusSyncReq
	StatusSyncResp = worker.StatusSyncResp

	Worker interface {
		LifeCircle(ctx context.Context, in *LifeCircleReq, opts ...grpc.CallOption) (*LifeCircleResp, error)
		StatusSync(ctx context.Context, in *StatusSyncReq, opts ...grpc.CallOption) (*StatusSyncResp, error)
	}

	defaultWorker struct {
		cli zrpc.Client
	}
)

func NewWorker(cli zrpc.Client) Worker {
	return &defaultWorker{
		cli: cli,
	}
}

func (m *defaultWorker) LifeCircle(ctx context.Context, in *LifeCircleReq, opts ...grpc.CallOption) (*LifeCircleResp, error) {
	client := worker.NewWorkerClient(m.cli.Conn())
	return client.LifeCircle(ctx, in, opts...)
}

func (m *defaultWorker) StatusSync(ctx context.Context, in *StatusSyncReq, opts ...grpc.CallOption) (*StatusSyncResp, error) {
	client := worker.NewWorkerClient(m.cli.Conn())
	return client.StatusSync(ctx, in, opts...)
}
