// Code generated by goctl. DO NOT EDIT!
// Source: worker.proto

package server

import (
	"github.com/Awadabang/wasser/internal/logic"
	"github.com/Awadabang/wasser/internal/svc"
	"github.com/Awadabang/wasser/types/worker"
)

type WorkerServer struct {
	svcCtx *svc.ServiceContext
	worker.UnimplementedWorkerServer
}

func NewWorkerServer(svcCtx *svc.ServiceContext) *WorkerServer {
	return &WorkerServer{
		svcCtx: svcCtx,
	}
}

func (s *WorkerServer) LifeCircle(stream worker.Worker_LifeCircleServer) error {
	l := logic.NewLifeCircleLogic(stream.Context(), s.svcCtx)
	return l.LifeCircle(stream)
}

func (s *WorkerServer) StatusSync(stream worker.Worker_StatusSyncServer) error {
	l := logic.NewStatusSyncLogic(stream.Context(), s.svcCtx)
	return l.StatusSync(stream)
}
