// Code generated by goctl. DO NOT EDIT!
// Source: worker.proto

package server

import (
	"context"

	"github.com/Awadabang/wasser/internal/logic"
	"github.com/Awadabang/wasser/internal/svc"
	"github.com/Awadabang/wasser/types/worker"
)

type WorkerServer struct {
	svcCtx *svc.ServiceContext
	worker.UnimplementedWorkerServer
}

func NewWorkerServer(svcCtx *svc.ServiceContext) *WorkerServer {
	return &WorkerServer{
		svcCtx: svcCtx,
	}
}

func (s *WorkerServer) LifeCircle(ctx context.Context, in *worker.LifeCircleReq) (*worker.LifeCircleResp, error) {
	l := logic.NewLifeCircleLogic(ctx, s.svcCtx)
	return l.LifeCircle(in)
}

func (s *WorkerServer) StatusSync(ctx context.Context, in *worker.StatusSyncReq) (*worker.StatusSyncResp, error) {
	l := logic.NewStatusSyncLogic(ctx, s.svcCtx)
	return l.StatusSync(in)
}
